OMZigak/KKUMER

.github/workflows/dev-cd.yml, .github/workflows/dev-ci.yml, .gitignore, .gitmodules, Dockerfile, build.gradle
- closed #1
- submodule 적용을 통한 yaml 파일 형상관리 구현
- docker를 이용한 cicd 구현
- EC2 내부에 deploy.sh 스크립트를 통한 blue green 배포 구현
=> [init] 배포 세팅

src/main/java/org/kkumulkkum/server/auth/CustomJwtAuthenticationEntryPoint.java, src/main/java/org/kkumulkkum/server/auth/JwtAuthenticationFilter.java, src/main/java/org/kkumulkkum/server/auth/JwtExceptionFilter.java, src/main/java/org/kkumulkkum/server/config/SecurityConfig.java, src/main/java/org/kkumulkkum/server/controller/TestController.java, src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java
- closed #17
- SecurityConfig에서 whitelist에 API를 추가해줘도 filter는 지나가기 때문에 JwtAuthenticationFilter에서 token이 필요 없는 API의 경우에 null을 jwt로 인지하고 값을 얻어오려해 에러가 나는 부분을 if문을 통해 수정해주었습니다.
https://github.com/OMZigak/KKUM_SERVER/blob/4946204125d3b3c31972169c1871b6a1e1970275/src/main/java/org/kkumulkkum/server/auth/JwtAuthenticationFilter.java#L30-L36
- filter단에서 일어나는 Jwt Exception들을 상황에 맞는 응답값으로 바꿔주기 위해 JwtExceptionFilter를 생성하고 AuthenticationEntryPoint를 수정했습니다.
- JwtExceptionFilter를 JwtAuthenticationFilter 전에 넣고 try문으로 다음 filter를 실행시킴을 통해 jwtExceptionFilter에서 catch로 exception을 받을 수 있습니다.
https://github.com/OMZigak/KKUM_SERVER/blob/4946204125d3b3c31972169c1871b6a1e1970275/src/main/java/org/kkumulkkum/server/auth/JwtExceptionFilter.java#L21-L32
- …
=> [fix] Jwt 예외 처리 추가 및 TestToken 발급 추가

build.gradle, src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/AppleFeignClient.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/dto/ApplePublicKey.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/dto/ApplePublicKeys.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/service/AppleService.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/verify/AppleJwtParser.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/verify/PublicKeyGenerator.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/KakaoFeignClient.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/dto/KakaoAccount.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/dto/KakaoUserDto.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/dto/SocialUserDto.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/service/KakaoService.java, src/main/java/org/kkumulkkum/server/config/FeignClientConfig.java, src/main/java/org/kkumulkkum/server/config/SecurityConfig.java, src/main/java/org/kkumulkkum/server/controller/AuthController.java, src/main/java/org/kkumulkkum/server/domain/Token.java, src/main/java/org/kkumulkkum/server/domain/UserInfo.java, src/main/java/org/kkumulkkum/server/dto/auth/request/UserLoginDto.java, src/main/java/org/kkumulkkum/server/exception/UserException.java, src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java, src/main/java/org/kkumulkkum/server/exception/code/UserErrorCode.java, src/main/java/org/kkumulkkum/server/repository/TokenRepository.java, src/main/java/org/kkumulkkum/server/repository/UserRepository.java, src/main/java/org/kkumulkkum/server/service/auth/AuthService.java, src/main/java/org/kkumulkkum/server/service/auth/TokenSaver.java, src/main/java/org/kkumulkkum/server/service/user/UserRetriever.java, src/main/java/org/kkumulkkum/server/service/user/UserSaver.java, src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java, src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoSaver.java
- closed #10 
- openFeign 관련 세팅했습니다.
- 카카오 로그인 openFeign 관련 코드 작성 및 유저 정보를 받아오기 위한 KakaoService를 구현했습니다.
- Apple 토큰을 받아서 사용자의 공개키를 확인하고, 이를 사용하여 토큰에서 클레임을 추출한 뒤 사용자의 고유 식별자와 이메일 정보를 가져오는 AppleService를 구현했습니다.
- 소셜 로그인 로직을 구현하였습니다.
=> [feat] 소셜 로그인 구현

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/controller/MeetingController.java, src/main/java/org/kkumulkkum/server/domain/BaseTimeEntity.java, src/main/java/org/kkumulkkum/server/domain/Meeting.java, src/main/java/org/kkumulkkum/server/dto/meeting/request/MeetingCreateDto.java, src/main/java/org/kkumulkkum/server/dto/meeting/request/MeetingRegisterDto.java, src/main/java/org/kkumulkkum/server/dto/meeting/response/CreatedMeetingDto.java, src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java, src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingsDto.java, src/main/java/org/kkumulkkum/server/dto/member/MemberUserInfoDto.java, src/main/java/org/kkumulkkum/server/dto/member/response/MemberDto.java, src/main/java/org/kkumulkkum/server/dto/member/response/MembersDto.java, src/main/java/org/kkumulkkum/server/exception/UserException.java, src/main/java/org/kkumulkkum/server/exception/code/BusinessErrorCode.java, src/main/java/org/kkumulkkum/server/exception/code/MeetingErrorCode.java, src/main/java/org/kkumulkkum/server/exception/code/UserErrorCode.java, src/main/java/org/kkumulkkum/server/repository/MeetingRepository.java, src/main/java/org/kkumulkkum/server/repository/MemberRepository.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingRetriever.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingSaver.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java, src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java, src/main/java/org/kkumulkkum/server/service/member/MemberSaver.java, src/main/java/org/kkumulkkum/server/service/user/UserRetriever.java
- closed #16
- Meeting 도메인과 관련된 API들을 제작 완료했습니다.
- 기본 이미지의 경우 클라이언트가 null이 아닌 기본 imgUrl을 요청해서 해당 작업을 진행해보았습니다.
- 다만 기본 이미지의 url이 노출될 경우 S3 보안에 문제가 있을 수 있다 판단하여 yml 파일로 내용을 빼두었습니다.
=> [feat] Meeting 관련 API 생성

src/main/java/org/kkumulkkum/server/config/SecurityConfig.java, src/main/java/org/kkumulkkum/server/controller/AuthController.java, src/main/java/org/kkumulkkum/server/dto/auth/request/UserLoginDto.java, src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java, src/main/java/org/kkumulkkum/server/repository/TokenRepository.java, src/main/java/org/kkumulkkum/server/service/auth/AuthService.java, src/main/java/org/kkumulkkum/server/service/auth/TokenRemover.java, src/main/java/org/kkumulkkum/server/service/auth/TokenRetriever.java, src/main/java/org/kkumulkkum/server/service/auth/TokenSaver.java
- closed #20 
- 소셜 로그인 로그아웃 로직 구현했습니다. (리프레시 토큰 삭제)
- jwt 토큰 reissue(재발급) 로직 구현했습니다. (재발급 시에 AT, RT 모두 재발급할 수 있도록)
https://github.com/OMZigak/KKUM_SERVER/blob/d848599e1ce1bdf7350ec9a321e8a3af5fd100ce/src/main/java/org/kkumulkkum/server/controller/AuthController.java#L30-L36
여기서 `return ResponseEntity.ok().build(); ` 를 하는 경우도 있고, `return ResponseEntity.noContent().build(); ` 를 해주는 경우가 있던데, 무엇으로 하는 것이 더 좋을지 고민이 됩니다.
=> [feat] 소셜 로그인 로그아웃, jwt 토큰 reissue 구현

build.gradle, src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/config/AwsConfig.java, src/main/java/org/kkumulkkum/server/controller/UserController.java, src/main/java/org/kkumulkkum/server/domain/UserInfo.java, src/main/java/org/kkumulkkum/server/dto/user/request/ImageUpdateDto.java, src/main/java/org/kkumulkkum/server/dto/user/request/NameUpdateDto.java, src/main/java/org/kkumulkkum/server/dto/user/response/UserDto.java, src/main/java/org/kkumulkkum/server/dto/user/response/UserNameDto.java, src/main/java/org/kkumulkkum/server/exception/AwsException.java, src/main/java/org/kkumulkkum/server/exception/code/AwsErrorCode.java, src/main/java/org/kkumulkkum/server/exception/code/BusinessErrorCode.java, src/main/java/org/kkumulkkum/server/external/S3Service.java, src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java, src/main/java/org/kkumulkkum/server/service/user/UserService.java, src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java, src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoService.java
- closed #23 
- S3 클라우드 서비스를 이용하여 사용자의 프로필을 저장 및 삭제할 수 있도록 했습니다.
- 사용자 프로필 관련 API를 생성했습니다. (로그인한 유저 정보 조회, 사용자 프로필 사진 수정 및 삭제, 사용자 이름 수정)
=> [feat] 사용자 프로필 관련 API 생성 (S3 Multipart 관련)

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/controller/ParticipantController.java, src/main/java/org/kkumulkkum/server/controller/PromiseController.java, src/main/java/org/kkumulkkum/server/domain/Participant.java, src/main/java/org/kkumulkkum/server/exception/ParticipantException.java, src/main/java/org/kkumulkkum/server/exception/code/ParticipantErrorCode.java, src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantEditor.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
- closed #24
- Participant 엔티티 관련 도메인 중 시간 업데이트 API들을 제작 완료했습니다.
- 이전 상태가 완료되지 않았을 때 다음 상태를 업데이트하지 못하도록 검증하는 로직이 있습니다.
https://github.com/OMZigak/KKUM_SERVER/blob/55b64258967a97de61f169622144931551001f69/src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java#L48-L73
=> [feat] 참여자 도메인 API 일부 생성

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/annotation/IsMember.java, src/main/java/org/kkumulkkum/server/annotation/IsParticipant.java, src/main/java/org/kkumulkkum/server/aspect/MemberCheckAspect.java, src/main/java/org/kkumulkkum/server/aspect/ParticipantCheckAspect.java, src/main/java/org/kkumulkkum/server/controller/ParticipantController.java, src/main/java/org/kkumulkkum/server/controller/PromiseController.java, src/main/java/org/kkumulkkum/server/exception/MemberException.java, src/main/java/org/kkumulkkum/server/exception/code/MemberErrorCode.java, src/main/java/org/kkumulkkum/server/repository/MemberRepository.java, src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java, src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
- closed #35 
- IsMember 커스텀 어노테이션을 만들었습니다.
- IsMember에 promiseId의 parameter index를 넣거나 IsMember에 meetingId의 parameter index를 넣는 방법으로 모임에 속한 Member가 맞는지 검증합니다. 입력하지 않은 정보에 대해서는 검증하지 않고 둘 중 하나만 있어도 사용 가능합니다.
- 사용 예시
https://github.com/OMZigak/KKUM_SERVER/blob/308b56cc58403e0b4b2e582cef64c50825590183/src/main/java/org/kkumulkkum/server/controller/PromiseController.java#L23-L29
https://github.com/OMZigak/KKUM_SERVER/blob/308b56cc58403e0b4b2e582cef64c50825590183/src/main/java/org/kkumulkkum/server/controller/ParticipantController.java#L56-L60
- IsParticipant도 필요한줄알고 만들었는데 필요가 없네요... 혹시 나중에 사용처가 생길 수 있으니 일단 두겠습니다. 후에도 사용되지 않는다면 삭제합시다.
IsMember에서 meetingId나 promiseId 둘 다 검증에 사용하기 위해 default 값을 입력하고 …
=> [feat] 권한 확인 Annotation 제작

src/main/java/org/kkumulkkum/server/controller/PromiseController.java, src/main/java/org/kkumulkkum/server/domain/UserInfo.java, src/main/java/org/kkumulkkum/server/dto/user/response/UserDto.java, src/main/java/org/kkumulkkum/server/exception/code/PromiseErrorCode.java, src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java, src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java, src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java, src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java
- closed #41 
- 약속 완료 API에 빠져있던 로직을 추가하였습니다.
- me에서 지각 총합을 초로 보여주던 것을 수정했습니다.
=> [fix] 약속 완료 API 수정

src/main/java/org/kkumulkkum/server/controller/AuthController.java, src/main/java/org/kkumulkkum/server/domain/UserInfo.java, src/main/java/org/kkumulkkum/server/dto/auth/request/UserLoginDto.java, src/main/java/org/kkumulkkum/server/dto/auth/response/UserTokenDto.java, src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
- closed #46 
- userInfo 엔티티에 fcmToken 추가해주었습니다.
- signin할 때마다 fcmToken을 업데이트 해주도록 했습니다.
- 로그인시 반환되는 값에 user의 name을 추가해주었습니다.
=> [feat] 소셜 로그인 API 관련 수정 작업 (fcm Token 추가)

src/main/java/org/kkumulkkum/server/external/S3Service.java
- closed #50 
- S3Service에 이미지의 외부 URL을 생성하여 반환하도록 하여, API responseBody에도 외부 URL을 내려주도록 수정했습니다.
=> [fix] S3Service 이미지 외부 URL 생성

build.gradle, src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/config/FirebaseConfig.java, src/main/java/org/kkumulkkum/server/exception/FirebaseException.java, src/main/java/org/kkumulkkum/server/exception/code/BusinessErrorCode.java, src/main/java/org/kkumulkkum/server/exception/code/FirebaseErrorCode.java, src/main/java/org/kkumulkkum/server/external/FcmService.java, src/main/java/org/kkumulkkum/server/external/dto/FcmMessageDto.java, src/main/java/org/kkumulkkum/server/external/enums/FcmContent.java, src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
- closed #56
- FirebaseConfig 추가
- FcmService 추가
- 준비 시작, 이동 시작, 도착 완료 api에 알림 로직 추가
=> [feat] fcm 푸시 알림 구현

src/main/java/org/kkumulkkum/server/controller/MeetingController.java, src/main/java/org/kkumulkkum/server/dto/meeting/response/CreatedMeetingDto.java
- closed #79 
- 모임 생성 API에 반환 값에 meetingId 추가
=> [fix] 모임 생성 API에 반환 값에 meetingId 추가

src/main/java/org/kkumulkkum/server/controller/MeetingController.java, src/main/java/org/kkumulkkum/server/domain/Participant.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
- closed #81
- Members에서 본인을 제외할 수 있도록 변경
=> [fix] 모임 가입자 조회 API 쿼리 파라미터 추가

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java, src/main/java/org/kkumulkkum/server/log/filter/MDCFilter.java, src/main/java/org/kkumulkkum/server/log/util/HttpRequestUtil.java, src/main/java/org/kkumulkkum/server/log/util/MDCUtil.java
- closed #75
- GlobalExceptionHandler에서 핸들링하지 않는 Exception만 discord를 받도록 로그 레벨 수정
- 로그에 Method 정보를 입력
AOP를 사용하려는 의도가 특정 메소드에만 작동하도록 하는 것이었는데 이미 log level 조정으로 가능하여 AOP의 사용 이유를 상실했습니다.
추가적으로 회원가입 등의 이벤트에 AOP를 다는 것은 이해가 가나 그냥 에러를 AOP로 하는 이유까지는 찾지 못했습니다.
=> [fix] 로그 레벨 수정 및 로그에 정보 추가

src/main/java/org/kkumulkkum/server/auth/JwtExceptionFilter.java
- closed #86 
- 의미없는 알림이 오는 것을 제거했습니다. (에러 원인은 ATK 만료)
- reissue 테스트를 위해 ATK 수명을 1분으로 변경했습니다.
일단 메시지를 제거했는데 다음 리팩토링 때 어디어디에 메시지를 다는 것이 좋을지 같이 생각해봅시다.
=> [fix] 의미없는 로깅 알림 제거

src/main/java/org/kkumulkkum/server/controller/AuthController.java, src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java, src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
- closed #88
- 유효하지 않은 토큰일 시(invalid token) 에러메시지 수정
- 토큰 재발급 validation @NotBlank 로 수정
- 토큰 예외 처리 추가
=> [fix] 토큰 재발급 시 JWT 토큰 예외 처리

.gitignore, build.gradle, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/AppleFeignClient.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/dto/AppleTokenDto.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/service/AppleService.java, src/main/java/org/kkumulkkum/server/auth/openfeign/apple/verify/AppleClientSecretGenerator.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/KakaoFeignClient.java, src/main/java/org/kkumulkkum/server/auth/openfeign/kakao/service/KakaoService.java, src/main/java/org/kkumulkkum/server/constant/AuthConstant.java, src/main/java/org/kkumulkkum/server/controller/AuthController.java, src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java, src/main/java/org/kkumulkkum/server/repository/MemberRepository.java, src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java, src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java, src/main/java/org/kkumulkkum/server/service/auth/AuthService.java, src/main/java/org/kkumulkkum/server/service/member/MemberRemover.java, src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRemover.java, src/main/java/org/kkumulkkum/server/service/user/UserRemover.java, src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRemover.java
- closed #90 
- 카카오 연결 끊기 구현
- 애플 연결 끊기 구현
- 애플 연결 끊기의 경우, 애플 연동해제를 위해 https://appleid.apple.com/auth/revoke 를 사용하였고, 이 때 필요한 token을 만들기 위해  https://appleid.apple.com/auth/token 를 사용하였습니다.
- DB에서 유저 삭제
- participant -> member -> userInfo -> user 순으로 순차적으로 DB에서 삭제해주었습니다.
이번에 깜빡하고 커밋메시지에 이슈번호 다는 것을 깜빡했습니다.... 다음부턴 꼭 까먹지 않고 달도록 하겠습니다.!!!!!!!
=> [feat] 회원탈퇴 구현 

src/main/java/org/kkumulkkum/server/external/S3Service.java
- closed #91 
- multipart 이미지 관련 수정했습니다.
- HEIC 확장자 추가해주었습니다.
- 스프링 자체에서 멀티파트 이미지 용량을 1MB 이하로 막아, 5MB로 제한하도록 수정했습니다.
- NGINX 파일 업로드 용량 제한 설정해주었습니다.
=> [fix] S3 multipart 이미지 관련 수정 

src/main/java/org/kkumulkkum/server/controller/PromiseController.java, src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java, src/main/java/org/kkumulkkum/server/dto/promise/response/MainPromiseDto.java, src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseAddDto.java, src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDetailDto.java, src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java, src/main/java/org/kkumulkkum/server/dto/promise/response/PromisesDto.java, src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
- closed #94 
- 약속 날짜에 따라 dday에 음수와 양수가 모두 표시되도록 수정했습니다.
- 시간 형식을 "yyyy-MM-dd HH:mm:ss"로 통일했습니다.
- 특정 모임의 약속 목록 API에 promise가 사용자에게 속하는지 여부를 필터링하기 위한 isParticipant 쿼리 파라미터를 추가했습니다.
- 약속 상세 정보 조회 API에 사용자가 Promise에 참여하고 있는지 여부를 나타내는 isParticipant 필드를 추가했습니다.
약속 상세 정보 조회 API를 수정하면서 PromiseDto를 수정하게 되었는데, 이 Dto가 약속추가 API에도 사용되어서
약속추가 API에도 "isParticipant: true" (항상 true) 를 넣도록 명세를 수정해야할 것 같은데 어떻게 생각하시나용?
=> [feat] 약속 조회 관련 API 수정

src/main/java/org/kkumulkkum/server/aspect/ParticipantCheckAspect.java, src/main/java/org/kkumulkkum/server/controller/ParticipantController.java, src/main/java/org/kkumulkkum/server/controller/PromiseController.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRemover.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseRemover.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
- closed #96
- 약속 나가기 API 구현
- 약속 삭제하기 API 구현
- @IsParticipant 어노테이션 사용 시 ParticipantCheckAspect에서, 해당 유저가 참가자가 아닐 때 반환하는 오류를 '모임에 참여하지 않은 회원입니다' 에서 '참여하지 않은 약속입니다'로 변경
약속한 속한 모든 참가자들을 삭제할 때 `deleteAll`과는 다르게 단일 쿼리를 보내 성능이 향상된다는 `deleteAllInBatch`를 사용해보았습니다..!  그러나 `deleteAllInBatch`가 영속성 컨텍스트 관련 처리는 생략한다고 한다고 해서 적절한 선택을 한건지 고민이 됩니다.
=> [feat] 약속 나가기, 약속 삭제하기 API 구현

src/main/java/org/kkumulkkum/server/controller/PromiseController.java, src/main/java/org/kkumulkkum/server/domain/Promise.java, src/main/java/org/kkumulkkum/server/exception/code/MemberErrorCode.java, src/main/java/org/kkumulkkum/server/repository/MemberRepository.java, src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java, src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java, src/main/java/org/kkumulkkum/server/service/participant/ParticipantRetriever.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseEditor.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
- closed #98
- 약속 정보 수정
- 참여자 목록 수정
=> [feat] 약속 정보 수정 API 구현 

src/main/java/org/kkumulkkum/server/controller/MeetingController.java, src/main/java/org/kkumulkkum/server/domain/Meeting.java, src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingEditor.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingRemover.java, src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java, src/main/java/org/kkumulkkum/server/service/member/MemberRemover.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseRemover.java
- closed #100 
- 모임 수정 API 구현
- 모임 탈퇴 API 구현
=> [feat] 모임 수정, 탈퇴 API 구현 

src/main/java/org/kkumulkkum/server/domain/Promise.java, src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDetailDto.java, src/main/java/org/kkumulkkum/server/service/promise/PromiseEditor.java
- closed #104 
- 약속 수정 시, 장소 변경이 없는 경우를 대비하여 약속 상세 정보에 x, y 좌표를 추가해주었습니다.
- 약속 수정시 time도 수정될 수 있도록 수정했습니다.
=> [fix] 약속 수정 API 관련 수정 

src/main/java/org/kkumulkkum/server/auth/openfeign/apple/service/AppleService.java, src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java
- closed #106 
- 애플 회원탈퇴 시 authCode 입력 값을 확인하여 authCode가 비어있으면 400에러를 내도록 했습니다.
- 예외 객체 전체를 로그에 기록할 수 있도록 수정했습니다.
=> [fix] 애플 회원탈퇴 시 authCode 입력 값 확인 로직 추가

src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
- closed #117 
- 약속 나가기 시, 약속 참가자가 아무도 없게되면 약속 자체를 삭제하도록 수정했습니다.
=> [fix] 약속 나가기 시 약속 참여 인원에 따른 약속 삭제 

.github/workflows/dev-cd.yml, .github/workflows/prod-cd.yml
- closed #123 
- CI/CD 문제를 해결하기 위해서 deploy 라벨이 달려있지 않은 경우에만 develop cd가 일어나게 만들었습니다.
- 마찬가지로 deploy 라벨이 있는 경우에만 prod cd가 일어나게 만들었습니다.
PR label을 사용하는 것은 임시 방편 같은데 github의 release를 사용하면 이런 문제를 해결할 수 있을까 궁금하네요
=> [fix] CI/CD 수정

src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java
- closed #127 
- 일부 예외가 디스코드 메시지로 날라오지 않아 이를 해결했습니다.
- 해당 예외들은 다음과 같이 생겼습니다.
- 디버깅 결과 해당 예외 메시지에 String 값을 포함할 경우 String 값을 표현할 때 사용되는 "가 Json을 invalid하게 만들기 때문에 일어난 일임을 확인했습니다.
- 이 때문에 discord 웹훅 API가 요청을 날릴 때 400 에러가 떠서 일어난 문제입니다.
- 이를 방지하기 위해 replaceAll로 "를 '로 변경해주었습니다.
세상엔 예상치 못한 일들이 참 많군요...
=> [fix] 디스코드 로깅 오류 해결

.github/workflows/prod-cd.yml
GITHUB_OUTPUT에 version 환경 변수를 추가하는 echo문까지 잘못 삭제해버려서 다시 추가했습니다.
=> Release 1.0.0

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
- closed #144
- 핸들링되고 있지 않던 HttpMessageNotReadableException을 GlobalExceptionHandler에서 처리하도록 추가했습니다.
=> [fix] HttpMessageNotReadableException 핸들링 추가

build.gradle, src/main/java/org/kkumulkkum/server/external/FcmService.java
- closed #146
- 기존에 사용하고 있었던 sendMulticast 메소드가 deprecated되어 sendEachForMulticast로 바꿔주었습니다.
[참고링크](https://stackoverflow.com/questions/78947756/no-enum-constant-com-google-firebase-errorcode-unimplemented)
=> [fix] FCM deprecated method 변경

build.gradle, src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java, src/main/java/org/kkumulkkum/server/external/FcmService.java, src/main/java/org/kkumulkkum/server/repository/MemberRepository.java, src/main/java/org/kkumulkkum/server/service/auth/AuthService.java
=> Release v1.0.1
