src/main/java/org/kkumulkkum/server/advice/ResponseDtoAdvice.java
src/main/java/org/kkumulkkum/server/controller/TestController.java
src/main/java/org/kkumulkkum/server/dto/common/ErrorDto.java
src/main/java/org/kkumulkkum/server/dto/common/ResponseDto.java
src/main/java/org/kkumulkkum/server/dto/test/TestDto.java

- closed #3
- ResponseDto 생성
- 봉투 패턴 적용

[feat] Api 공통 응답 형태

---

.github/workflows/dev-cd.yml
build.gradle

- closed #7 
- copyYml task가 항상 작동하게 만들었습니다.
- 그에 따라 dev-cd.yml 파일에서 yml 파일 복사 부분을 제거했습니다.

[fix] submodule yml 복사 과정 수정

---

src/main/java/org/kkumulkkum/server/dto/common/ResponseDto.java

- closed #12
- 공통 응답 형태 success 추가

[feat] #12 공통 응답 형태 클라 요청 반영

---

src/main/java/org/kkumulkkum/server/config/JpaAuditingConfig.java
src/main/java/org/kkumulkkum/server/domain/BaseTimeEntity.java
src/main/java/org/kkumulkkum/server/domain/Meeting.java
src/main/java/org/kkumulkkum/server/domain/Member.java
src/main/java/org/kkumulkkum/server/domain/Participant.java
src/main/java/org/kkumulkkum/server/domain/Promise.java
src/main/java/org/kkumulkkum/server/domain/User.java
src/main/java/org/kkumulkkum/server/domain/UserInfo.java
src/main/java/org/kkumulkkum/server/domain/enums/DressUpLevel.java
src/main/java/org/kkumulkkum/server/domain/enums/Provider.java
src/main/java/org/kkumulkkum/server/domain/enums/Role.java
src/main/java/org/kkumulkkum/server/repository/MeetingRepository.java
src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
src/main/java/org/kkumulkkum/server/repository/UserInfoRepository.java
src/main/java/org/kkumulkkum/server/repository/UserRepository.java
src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
src/main/java/org/kkumulkkum/server/service/member/MemberService.java
src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java
src/main/java/org/kkumulkkum/server/service/user/UserService.java
src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoService.java

- closed #11 
- 작업 전 충돌을 줄이기 위한 entity, repository, service 생성
- 작업 전 충돌을 방지하기 위하여 entity, repository, service를 미리 만들어주었습니다.

[feat] 작업 전 기본 도메인 및 계층 세팅 

---

build.gradle
src/main/java/org/kkumulkkum/server/advice/ResponseDtoAdvice.java
src/main/java/org/kkumulkkum/server/annotation/UserId.java
src/main/java/org/kkumulkkum/server/auth/CustomAccessDeniedHandler.java
src/main/java/org/kkumulkkum/server/auth/CustomJwtAuthenticationEntryPoint.java
src/main/java/org/kkumulkkum/server/auth/JwtAuthenticationFilter.java
src/main/java/org/kkumulkkum/server/auth/UserAuthentication.java
src/main/java/org/kkumulkkum/server/auth/UserId.java
src/main/java/org/kkumulkkum/server/auth/jwt/JwtTokenProvider.java
src/main/java/org/kkumulkkum/server/auth/jwt/JwtTokenValidator.java
src/main/java/org/kkumulkkum/server/config/SecurityConfig.java
src/main/java/org/kkumulkkum/server/constant/Constant.java
src/main/java/org/kkumulkkum/server/constant/Constants.java
src/main/java/org/kkumulkkum/server/dto/auth/response/JwtTokenDto.java
src/main/java/org/kkumulkkum/server/exception/AuthException.java
src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java

- closed #9 
- Spring Security및 JWT 관련 설정 코드를 작성했습니다.
- UserId 커스텀 어노테이션 제작했습니다.
- 코드 포맷팅을 통일하였습니다. (한줄 띄기)

[feat] Spring Security, JWT 설정 

---

src/main/java/org/kkumulkkum/server/controller/PromiseController.java
src/main/java/org/kkumulkkum/server/domain/enums/DressUpLevel.java
src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java
src/main/java/org/kkumulkkum/server/dto/promise/response/PromisesDto.java
src/main/java/org/kkumulkkum/server/exception/PromiseException.java
src/main/java/org/kkumulkkum/server/exception/code/PromiseErrorCode.java
src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java
src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java

- closed #28 
- 특정 모임의 약속 목록, 약속 상세 정보 조회 API 구현했습니다.

[feat] 약속 관련 API 구현

---

src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java

- closed #39 
- 지각자가 도착완료 버튼을 누르지 않았을 때에도(arrivalAt이 null인 경우) 지각자로 처리하도록 수정하였습니다.

[feat] 약속 지각 상세 조회 API 추가 작업

---

src/main/java/org/kkumulkkum/server/annotation/IsMember.java
src/main/java/org/kkumulkkum/server/aspect/MemberCheckAspect.java

- closed #42 
- 권한 확인을 위한 annotation 조건문 수정

[fix] 권한 확인용 annotation 조건문 수정

---

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
src/main/java/org/kkumulkkum/server/controller/MeetingController.java
src/main/java/org/kkumulkkum/server/controller/UserController.java
src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java
src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingsDto.java
src/main/java/org/kkumulkkum/server/dto/member/response/MemberDto.java
src/main/java/org/kkumulkkum/server/dto/participant/ParticipantStatusUserInfoDto.java
src/main/java/org/kkumulkkum/server/dto/participant/response/LateComerDto.java
src/main/java/org/kkumulkkum/server/dto/participant/response/ParticipantDto.java
src/main/java/org/kkumulkkum/server/dto/promise/response/MainPromiseDto.java
src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java
src/main/java/org/kkumulkkum/server/dto/promise/response/PromisesDto.java
src/main/java/org/kkumulkkum/server/dto/user/response/UserDto.java
src/main/java/org/kkumulkkum/server/exception/code/AuthErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/AwsErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/BusinessErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/MeetingErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/MemberErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/OpenApiErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/ParticipantErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/PromiseErrorCode.java
src/main/java/org/kkumulkkum/server/exception/code/UserErrorCode.java
src/main/java/org/kkumulkkum/server/repository/ParticipantRepository.java
src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java
src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java
src/main/java/org/kkumulkkum/server/service/user/UserRetriever.java
src/main/java/org/kkumulkkum/server/service/user/UserService.java
src/main/java/org/kkumulkkum/server/service/userInfo/UserInfoRetriever.java

- closed #49 
- API 응답 관련 개선사항들을 적용했습니다.
- id라고 표시되던 내용들을 어떤 id인지 같이 표시해주었습니다.
- 에러에 대해서 더 세분화하였고 에러 코드와 에러 메시지를 정리하였습니다.
- API 명세들도 그에 맞게 모두 수정하였습니다.
이번 기회를 바탕으로 작업마다 develop 브랜치에서 파는 것을 한 번 더 명심하도록 합시다~

[fix] API 응답 관련 개선사항들 적용

---

src/main/java/org/kkumulkkum/server/service/participant/ParticipantService.java

- closed #58 
- 약속 참여자 목록 정렬 추가했습니다. (도착, 이동중, 준비중, 꾸물중 순)

[feat] 약속 참여자 목록 정렬 추가

---

src/main/java/org/kkumulkkum/server/controller/PromiseController.java
src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java
src/main/java/org/kkumulkkum/server/repository/MemberRepository.java
src/main/java/org/kkumulkkum/server/repository/PromiseRepository.java
src/main/java/org/kkumulkkum/server/service/member/MemberRetreiver.java
src/main/java/org/kkumulkkum/server/service/promise/PromiseRetriever.java
src/main/java/org/kkumulkkum/server/service/promise/PromiseService.java

- closed #65 
- member validation 오류 수정
- 약속 목록 정렬 추가 (약속 시간 가까운 순, 약속 생성 순)
- 생성 일자 jsonFormat 오류 수정 (DD -> dd)
- yml에서 accessToken 1분으로 수정

[fix] API 세부 수정 

---

src/main/java/org/kkumulkkum/server/controller/LocationController.java
src/main/java/org/kkumulkkum/server/external/NaverService.java
src/main/java/org/kkumulkkum/server/external/dto/LocationDto.java
src/main/java/org/kkumulkkum/server/external/dto/LocationsDto.java

- closed #67 
- API 명세와 다른 부분 수정

[fix] location 검색 API 수정

---

src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
src/main/java/org/kkumulkkum/server/controller/MeetingController.java
src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingIdDto.java
src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java

- closed #71 
- 모임 가입 API에 응답값 추가 (meetingId)

[fix] 모임 가입 API에 응답값 추가

---

build.gradle
src/main/java/org/kkumulkkum/server/advice/GlobalExceptionHandler.java
src/main/java/org/kkumulkkum/server/config/FilterConfig.java
src/main/java/org/kkumulkkum/server/exception/code/BusinessErrorCode.java
src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java
src/main/java/org/kkumulkkum/server/log/discord/DiscordWebHook.java
src/main/java/org/kkumulkkum/server/log/filter/MDCFilter.java
src/main/java/org/kkumulkkum/server/log/filter/ServletWrappingFilter.java
src/main/java/org/kkumulkkum/server/log/model/Author.java
src/main/java/org/kkumulkkum/server/log/model/EmbedObject.java
src/main/java/org/kkumulkkum/server/log/model/Field.java
src/main/java/org/kkumulkkum/server/log/model/Footer.java
src/main/java/org/kkumulkkum/server/log/model/Image.java
src/main/java/org/kkumulkkum/server/log/model/JsonObject.java
src/main/java/org/kkumulkkum/server/log/model/Thumbnail.java
src/main/java/org/kkumulkkum/server/log/util/ApiCallUtil.java
src/main/java/org/kkumulkkum/server/log/util/HttpRequestUtil.java
src/main/java/org/kkumulkkum/server/log/util/MDCUtil.java
src/main/java/org/kkumulkkum/server/log/util/StringUtil.java
src/main/java/org/kkumulkkum/server/log/wrapper/CachedBodyRequestWrapper.java
src/main/java/org/kkumulkkum/server/log/wrapper/CachedBodyServletInputStream.java
src/main/resources/console-appender.xml
src/main/resources/discord-appender.xml
src/main/resources/logback-spring.xml

- closed #62
- 에러가 일어났을 때 디스코드로 알림을 보내는 작업을 진행했습니다.
- 정리된 내용은 노션>작업실을 확인해주세요

[feat] 디스코드 로깅 봇 추가

---

src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java

- closed #74
- 약속 상세 API에 약속 이름이 없어서 넣어주었습니당

[fix] 약속 상세 정보 조회 API에 이름 추가

---

src/main/java/org/kkumulkkum/server/dto/promise/response/PromiseDto.java
src/main/java/org/kkumulkkum/server/external/S3Service.java
src/main/java/org/kkumulkkum/server/log/filter/ServletWrappingFilter.java

- closed #77 
- 디스코드 로깅 설정 후 S3 이미지 업로드가 안되는 오류 수정
- S3이미지 수정(재업로드) 및 삭제시 S3에서 이미지가 삭제되지 않는 오류 수정
- 자세한 내용은 작업실 `로깅 후 s3 이미지 업로드가 안돼요… `에 있습니다...
[//]: #
-  develop에서 commit하고 다른 브랜치에서 push하는 실험을 하면서 먼가 어려움이 생겼습니다..... 흙흑.,.,,,.,,
- 그리고 ServletWrappingFilter를 수정한거라.. 이거 머지되고도 로깅 잘 되는지 확인 한 번 해봐야할 것 같습니다..!

[fix] Multipart 관련 오류 수정

---

src/main/java/org/kkumulkkum/server/dto/meeting/MeetingMetCountDto.java
src/main/java/org/kkumulkkum/server/dto/meeting/response/MeetingDto.java
src/main/java/org/kkumulkkum/server/repository/MeetingRepository.java
src/main/java/org/kkumulkkum/server/service/meeting/MeetingRetriever.java
src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java

- closed #84
- fetch join으로 인해 count가 잘못 계산되는 오류 해결
- 트러블 슈팅은 Notion의 JOIN FETCH 관련 항목 참고
- metCount에 완료된 약속 수가 아닌 현재 멤버 수를 반환하는 오류 해결

[fix] API count 관련 이슈 해결

---

src/main/java/org/kkumulkkum/server/constant/AuthConstant.java

- closed #108
- 상수 kakaoAK -> KakaoAK 로 변경했습니다.

[fix] Kakao 탈퇴 시 연결끊기 오류 해결

---

.github/workflows/prod-cd.yml
.github/workflows/prod-ci.yml
Dockerfile-prod
src/main/resources/logback-spring.xml

- closed #110 
- ci/cd prod 스크립트 작성
- application prod 버전 작성
- github secrets prod 버전 작성
- dockerfile prod 버전 작성
- discord prod 추가

[feat] 운영 서버 배포 준비

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml
src/main/java/org/kkumulkkum/server/log/discord/DiscordAppender.java

prod Deploy

---

src/main/java/org/kkumulkkum/server/controller/TestController.java

- closed #137
- hotfix 테스트용 PR입니다.

[hotfix] 테스트를 위한 hotfix & TestController 일부 기능 삭제

---

src/main/java/org/kkumulkkum/server/controller/TestController.java

Sync Develop

---

src/main/java/org/kkumulkkum/server/service/meeting/MeetingService.java

- closed #134 
- 혼자 약속을 만들고 모임을 나갈 시, 참여자가 없는 비어있는 약속을 삭제했습니다.

[fix] 모임 나가기 세부사항 수정 
